# This is a basic workflow to help you get started with Actions
name: Download profile image

# Controls when the workflow will run
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |

      # Install dependencies    
      - name : git clone and commit
        run : |
          git config --global user.name "biud436"
          git config --global user.email "biud436@gmail.com"
          
          git clone https://github.com/biud436/biud436
          cd biud436
          curl "https://blog-api.biud436.com/image/shake-profile?text=I%27m%20a%20Backend%20Server%20Application%20Developer.&color=ffffff&textSize=20&y=152&username=biud436&seed=$RANDOM" > profile.svg
          git add .
          git commit -m "feat: Update profile.svg"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.METRICS_TOKEN }}
          branch: ${{ github.ref }}

