# This is a basic workflow to help you get started with Actions
name: Download profile image

# Controls when the workflow will run
on:
    # 3시간마다 업데이트
    schedule: [{ cron: "0 */3 * * *" }]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: { branches: ["master", "main"] }

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3

            # Runs a set of commands using the runners shell
            - name: Run a multi-line script
              run: |
            - name: Download SVG image
              run: |
                  rm -rf ./profile.svg
                  curl "https://github-readme-stats-biud436.vercel.app/api?username=biud436&show_icons=true&locale=en&theme=transparent&count_private=true&hide=contribs,prs" > stats.svg
                  git add .
            # Install dependencies
            - name: Commit files
              run: |
                  git config --local user.name "biud436"
                  git config --local user.email "biud436@gmail.com"
                  git commit -m "feat: Update stats.svg" -a
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.METRICS_TOKEN }}
                  branch: ${{ github.ref }}
